In [25]:

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
customer_id = df['customerID']
data = df.drop(['customerID'], axis=1)

cols = ['SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

# data['gender'] = data['gender'].map({'Male': 1, 'Female': 0})
# cols_without_yesno = []

# print(df['Partner'].value_counts().index.tolist())    # check output, can be misarranged

# for col in cols:
    
#     if df[col].dtype == 'object':
#         # print(df[col].value_counts())
#         pass

#     if df[col].value_counts().index.tolist() != ['No', 'Yes']:
#         cols_without_yesno.append(col)

#     if df[col].value_counts().index.tolist() == ['No', 'Yes']:
#         df[col] = df[col].map({'Yes': 1, 'No': 0})

data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

data.sample(5)

      gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
4096  Female              0      No  ...          89.40       1871.15    No
1340  Female              0     Yes  ...          56.05           NaN    No
241     Male              0      No  ...         109.20       7878.30    No
3624  Female              1     Yes  ...          96.10       6019.35    No
395   Female              0      No  ...          90.05       5965.95    No

[5 rows x 20 columns]

In [31]:
cols_without_yesno = []

for col in cols:
    # print(data[col].nunique())
    if data[col].nunique() > 2:
        cols_without_yesno.append(col)

cols_without_yesno

['MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaymentMethod']

In [27]:
from sklearn.model_selection import train_test_split

x = data.drop(['Churn'], axis=1)
y = data['Churn']
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [28]:
x_train.sample(5)

      gender  SeniorCitizen  ... MonthlyCharges TotalCharges
1567  Female              0  ...          67.80       653.15
3759    Male              0  ...          89.35       631.85
5998    Male              0  ...          20.05      1036.00
2936    Male              0  ...         102.65      4108.15
1394  Female              0  ...         110.80      6840.95

[5 rows x 19 columns]

### Transformers

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OrdinalEncoder

# trf1 = ColumnTransformer(transformers=[
#     ('impute_totalcharges', SimpleImputer(), [18])
# ], remainder='passthrough')

# trf2 = ColumnTransformer(transformers=[
#     ("mapping", OrdinalEncoder(), [0])
# ], remainder='passthrough')

# trf3 = ColumnTransformer(transformers=[
#     ("ohe", OneHotEncoder(handle_unknown="ignore"), [6, 7, 8, 9, 10, 11, 12, 13, 14, 16])
# ], remainder='passthrough')

# trf4 = SelectKBest(k=8)

# trf5 = RandomForestClassifier()


processor = ColumnTransformer(transformers=[
    ("Gender_encoding", OrdinalEncoder(), ['gender']),
    ("Missing_values", SimpleImputer(), ['TotalCharges']),
    ("OHE", OneHotEncoder(), cols_without_yesno)
], remainder='passthrough')

In [ ]:
from sklearn.pipeline import make_pipeline, Pipeline

pipe = Pipeline([
    # ('trf1',trf1),
    # ('trf2',trf2),
    # ('trf3',trf3),
    # ('trf4',trf4),
    # ('trf5',trf5)
    ('processor', processor),
    ('select_features', SelectKBest(mutual_info_classif, k=8))
    ('')
])

# pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)
pipe.fit(x_train, y_train)

ValueError: could not convert string to float: 'Female'